autowire:
  normal:
    github.com/alibaba/ioc-golang/extension/db/gorm.GORMDB:
      dev-mysql:
        param:
          host: "127.0.0.1"
          port: 3306
          username: "root"
          password: "root"
          dbname: "dev"

config:
  initSqlFilePath: ./configs/data/dev_shopping_db_init.sql

debug:
  app-name: product